- docs/how_to.md
- service_provider_example/resources/swagger.yaml
- terraform_provider_api/api_spec_analyser.go
- terraform_provider_api/resource_info.go
Add support for basePath. Swagger files allow users to specify a base path from which all the resources will be under.
For instance, consider the below swagger config:
```
host: "localhost:8443"
basePath: "/api"
```
This should get translated into the following http call to resource - http://host.com/api/resource - if base path is specified. This Pull Request adds support for that.
Fixes: #3 
> Add support for base path

- docs/how_to.md
- service_provider_example/resources/swagger.yaml
- terraform_provider_api/auth.go
- terraform_provider_api/auth_test.go
- terraform_provider_api/provider_factory.go
- terraform_provider_api/resource_factory.go
Having the ability to specify a security scheme globally reduces the amount of boiler plate needed in the swagger file. With this improvement, users will be able to specify a global security scheme which will be applicable to all the operations. Operations, on the other hand, should be able to override the global config on the operation level by defining the security policy.
Example of global configuration:
````
security:
- ApiKeyHeaderAuth: []
- ApiKeyQueryAuth: []
````
Example of operation level override:
````
paths:
/billing_info:
get:
summary: Gets the account billing info
security:
- ApiKeyQueryAuth: []
````
Does this Pull Request resolve any …
> Add support for global security schemes

- Makefile
- examples/swaggercodegen/api/resources/swagger.yaml
- examples/swaggercodegen/main.tf
- openapi/resource_factory.go
Fixes issue where using the 'x-terraform-field-name' extension to override a property value with a preferred one terraform would exploit.
Fixes: #43 
> Bug fix/handle properly terraform field extension

- openapi/api_spec_analyser.go
- openapi/api_spec_analyser_test.go
This PR fixes a bug in the apiSpecAnalyser where paths deemed non terraform compliant would throw an error and instead of ignoring those an error would be returned to the parent function causing terraform to stop the execution right away.
- updated unit test to cover more test scenarios
- updated resourceNameRegex to handle subresources too
Fixes: #46 
> update analyser to not throw an error when running into non compliant resources

- docs/how_to.md
- examples/swaggercodegen/api/resources/swagger.yaml
- openapi/resource_factory.go
- this change is needed specially when terraform handles updates/deletions doing a
refresh first (performing a read call) in which case if an error is thrown then updates/deletes will
not work as terraform will stop the execution right away. The reading handler
will wipe out the state of a resource if its not found remotely which is
the expected behaviour
- allow 404 when checking returned status code on deletion. if 404 that means
resource has been deleted already...also even if polling is enabled, the polling
mechanism will also capture that and return successfully
- increased the timeout duration to meet service providers APIs where operations
take more than 1 min. Setting it to 10 tentatively for now.
- save one extra read call by just using the payload received from either the first …
> check errors when reading and if error is NotFound then return nil as expected

- main_test.go
- openapi/provider_factory.go
- openapi/provider_factory_test.go
This ensures if a security definitions that is not global is used for instance inside an operation the provider can still be configured accordingly
Fixes: #68 
> register to the provider schemes security definitions that are not global schemes

- openapi/provider_configuration.go
- openapi/provider_configuration_test.go
- openapi/provider_factory.go
If the security definitions or header values were not provided in the terraform configuration the error displayed was not very user friendly and would lead to confusion. This makes sure that proper error message is displayed in such scenario so the user can fix the issue and provide the corresponding missing values in the terraform configuration.
> Enhance error output when tf config is missing values for headers and security definitions

- openapi/openapi_client_test.go
- openapi/provider_configuration.go
- openapi/provider_configuration_test.go
- this was introduced when multiregion support was added on the provider
levelm since getRegion is accessing the dataResource object which can
potentially be accessed in parallel by terraform causing concurrent map
issues
Fixes: #88 
- [ x] Bug-fix (change that fixes current functionality)
> fix map race condition issue

- Makefile
- examples/swaggercodegen/api/api/cdn.go
- main.go
- openapi/headers.go
- openapi/openapi_client.go
- openapi/openapi_client_test.go
- openapi/openapi_spec_authenticator_api_test.go
- openapi/openapi_spec_authenticator_apikey_test.go
- openapi/openapi_spec_security_definition_apikey_header_bearer.go
- openapi/openapi_spec_security_definition_apikey_header_bearer_test.go
- openapi/openapi_spec_security_definition_apikey_header_test.go
- openapi/openapi_spec_security_definition_apikey_query_test.go
- openapi/openapi_spec_security_definitions_test.go
- openapi/openapi_v2_security_test.go
- openapi/provider_factory_test.go
- openapi/version/version.go
- openapi/version/version_test.go
Response to feature request: https://github.com/dikhan/terraform-provider-openapi/issues/83
User agent information is now appended to request header in ```performRequest``` using the following new functions: 
* ```BuildUserAgent```
* ```appendUserAgentHeader```
> add user agent support 

- docs/how_to.md
- go.mod
- go.sum
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- openapi/provider_test.go
Remove not needed check that was preventing resources from being registered if the model definitions were externalized (meaning the swagger file did not contain a definition section)
- [x ] I have read and followed the [CONTRIBUTING](https://github.com/dikhan/terraform-provider-api/blob/master/.github/CONTRIBUTING.md) guidelines
> remove check that was preventing resources from being registered successfully

- .gitignore
- .travis.yml
- Makefile
- README.md
Push code coverage report on CI builds 
> push code cov report from ci build too

- main.go
- main_test.go
Enable multiple digits in regex that checks binary name and extracts the provider name
Fixes: #172 
> support provider name with version containing multiple digits (e,g: terraform-provider-openapi_v0.20.0)

- go.mod
- openapi/common.go
- openapi/common_test.go
- openapi/resource_factory.go
- openapi/resource_factory_test.go
- tests/integration/resource_cdns_test.go
Fixes: #169 
Also updated the immutable properties error messaging to be more readable.
> Remove error out when API returns properties that are not specified in the resource definition model

- go.mod
- go.sum
- openapi/openapi_v2_spec_analyser_test.go
Fix assertion on TestGetTerraformCompliantResources that fails when sub-resource parent isn't at index 2 of actualResourceSchema.Properties. This is causing a failing build on master.
> Fix subresource parent assertion in TestGetTerraformCompliantResources

- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
Please link to the issue number here: #233 
P.S: Intentionally not making the PR title a feature request as it is not desired for this change to be outlined in the next release change-log. 
> Add support for x-ignore-order

- pkg/terraformdocsgenerator/README.md
- pkg/terraformdocsgenerator/example_provider_documentation_output.html
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #265 
> [BugFix: Issue #265] Add deterministic order for resources and data sources rendered with the `OpenAPI Terraform Documentation Renderer`

- docs/how_to.md
- openapi/openapi_spec_resource_schema_definition_property.go
- openapi/openapi_spec_resource_schema_definition_property_test.go
Terraform currently does not support setting up Default values for TypeList. Otherwise an error will be thrown by Terraform on runtime like this: `Default is not valid for lists`
Please link to the issue number here (issue will be closed when PR is merged): Closes #286 
> [BugFix: Issue #286] Do not populate terraform schema Default field if property type is list

- openapi/openapi_spec_resource_schema_definition_property.go
- openapi/openapi_spec_resource_schema_definition_property_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_properties.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_properties_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
terraformdocsgenerator does not render optional computed properties with default values in the arguments section
- Added helper method IsOptionalComputedWithDefault to check within the renderer
whether the property with default value is to be treated as optional computed too.
- Renderer now includes both optioanl computed properties and optioanl computed properties
with default values in the arguments section along with the default value if populated.
- Other tests were failing due to ordering not matching anymore. This is due to
the hashstructure.Hash now computing the new property added which changed the hash order.
Please link to the issue number here (issue will be closed when PR is merged): Closes #289 
What type of change does your code introduce to the provider? Please put an `x` …
> Render in arguments section optional computed properties with default values

- docs/plugin_configuration_schema.md
- openapi/plugin_config.go
- openapi/plugin_config_schema.go
- openapi/plugin_config_schema_test.go
- openapi/plugin_config_services.go
- openapi/plugin_config_services_stub.go
- openapi/plugin_config_services_test.go
- openapi/plugin_config_test.go
- openapi/terraformutils/terraform_utils.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #318 
More context:
- After deep evaluation as to whether supporting a new version of the Schema config would make sense, the final conclusion was that the overhead incurred to support multiple versions would not pay off since the goal was to eliminate this functionality all together considering it's no longer providing any value preventing users from switching between different provider versions across different terraform projects that may pin to different versions of this provider. Hence, maintaining support for two parallel configurations in this case would result into unpredictable behaviours with users using SchemaV1 which is not desired.
- Nevertheless, since this changeset updates the contract of …
> [BugFix: Issue #318] Deprecate plugin_version property from OpenAPI config file SchemaV1

- .travis.yml
Please link to the issue number here (issue will be closed when PR is merged): Closes #335
- Pinning to v1.6.3 until the repo supports Go 1.18
- gorelease installation works as expected and the version is pinned to the expected version:
```
$ go install github.com/goreleaser/goreleaser@v1.6.3
go: downloading github.com/goreleaser/goreleaser v1.6.3
go: downloading github.com/alecthomas/jsonschema v0.0.0-20211209230136-e2b41affa5c1
go: downloading github.com/apex/log v1.9.0
go: downloading github.com/caarlos0/ctrlc v1.0.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/muesli/coral v1.0.0
go: downloading github.com/muesli/mango-coral v1.0.1
go: …
```
> [BugFix: Issue #335] goreleaser latest version (1.7) introduced breaking changes requiring Go1.18

- Makefile
Follow-up fix for https://github.com/dikhan/terraform-provider-openapi/pull/337
- Travis does not allow secret env variables to be used in forks which results into all the PRs opened by external contributors to fail. By adding this docker logins will not be executed and therefore builds now may still fail due to docker free quota being reached (since the egres ip from travis is shared among all the hosts). This is preferable as at least there is a change that the build will pass, unfortunately Travis does not provide any solution for this at the moment.
Soure: https://docs.travis-ci.com/user/environment-variables/
Please link to the issue number here (issue will be closed when PR is merged): Closes #338 
*If you don't have an issue created, please create the issue first describing the …
> [BugFix: Issue #338] Skip docker login from forks

- Makefile
This PR fixes the release pipeline currently blocked due to the github-release-notes lib being added as a go mod dep and therefore causing the git state to become dirty before goreleaser is able to execute the release which makes it fail.
Example of release failing due to the above: https://app.travis-ci.com/github/dikhan/terraform-provider-openapi/jobs/567413504
````
18.55s$ make release-version
[INFO] No github-release-notes in /home/travis/gopath/bin:/home/travis/.gimme/versions/go1.16.15.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home …
```
> Fix release pipeline: Only install the binary and not add it to the mod deps
