dikhan/terraform-provider-openapi

- Makefile
Add Makefile for consistent builds in future.
Fixes: #
> Adding makefile

- .github/CONTRIBUTING.md
Add legal terms to meet Cisco requirements.
> Add more info about Licensing Code Contributions and Licensing

- terraform_provider_api/resource_factory.go
- terraform_provider_api/utils.go
- terraform_provider_api/utils_test.go
Add support for multiple response status codes
Fixes: #17 
> Add support for multiple response status codes

- .travis.yml
- Simple CI pipeline that triggers the units tests
Please add as many details as possible about the change here. 
Fixes: #6 
> Create CI pipeline

- .github/CONTRIBUTING.md
- terraform_provider_api/Makefile
- terraform_provider_api/api_spec_analyser.go
- terraform_provider_api/main.go
- terraform_provider_api/otf_vars.go
- terraform_provider_api/otf_vars_test.go
- terraform_provider_api/provider.go
- terraform_provider_api/provider_factory.go
- terraform_provider_api/resource_factory.go
- terraform_provider_api/resource_info.go
- terraform_provider_api/utils.go
Golint should be executed before running the unit tests same as gofmt and govet
Fixes: #22 
> Add lint target as a dependency of make test target

- docs/how_to.md
- terraform_provider_api/resource_factory.go
- terraform_provider_api/resource_info.go
- terraform_provider_api/resource_info_test.go
Please add as many details as possible about the change here. 
Fixes: #24 
> Enable a property other than 'id' to be considered as the main identifier

- terraform_provider_api/Gopkg.lock
- terraform_provider_api/resource_factory.go
- terraform_provider_api/vendor/github.com/dikhan/http_goclient/http_client.go
Updated http client dep and adde better logging containing response body
> Better http error logging

- docs/local_environment.md
- terraform_provider_api/Makefile
- terraform_provider_api/auth_test.go
- terraform_provider_api/provider.go
Please add as many details as possible about the change here. 
Fixes: #28 
> add support for OTF_INSECURE_SKIP_VERIFY

- docs/how_to.md
- examples/swaggercodegen/api/resources/swagger.yaml
- openapi/api_spec_analyser.go
- openapi/api_spec_analyser_test.go
- openapi/openapiutils/openapi_utils.go
- openapi/openapiutils/openapi_utils_test.go
- openapi/resource_info.go
- openapi/resource_info_test.go
> add support for multi region resources

- .goreleaser.yml
> enable windows support

- openapi/plugin_config_schema_test.go
- openapi/plugin_config_services_schema_property_configuration.go
- added a test to ensure marshal output is expected
- [] New feature (change that adds new functionality)
> use flow format for string arrays

- .travis.yml
- Gopkg.lock
- README.md
- vendor/github.com/jtolds/gls/stack_tags.go
> Feature/fix issues using go1.12.4

- README.md
- docs/terraform_version_upgrades/upgrading_to_terraform_0.12.md
- examples/swaggercodegen/main.tf
- examples/swaggercodegen/versions.tf
Please add as many details as possible about the change here. Does this Pull Request resolve any open issue?  If so, please make sure to link to that issue:
Fixes: #120 
> Feature/upgrade example configs to 0.12upgrade

- Dockerfile
- README.md
- go.mod
- go.sum
> Feature/update to 0.12.0 not rc

- go.mod
- go.sum
- openapi/openapi_client.go
- openapi/openapi_client_test.go
- openapi/openapi_spec_backend_configuration.go
- openapi/openapi_stub_backend_configuration.go
- openapi/openapi_v2_backend_configuration.go
- openapi/openapi_v2_backend_configuration_test.go
Raise an error when backend config has no httpSchemes configured
Fixes: #130  
> Raise an error when a swagger doc is analyzed with no schemes

- docs/how_to_subresources.md
- go.mod
- go.sum
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- openapi/openapi_v2_spec_analyser.go
- openapi/openapi_v2_spec_analyser_test.go
- tests/e2e/gray_box_cdns_test.go
> Honour parent preferred names in subresource name and parent property names

- README.md
- go.mod
- go.sum
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- openapi/openapi_v2_spec_analyser.go
- openapi/openapi_v2_spec_analyser_test.go
> GetMultiRegionHost error is ignored leading to malformed multiregion resources

- openapi/resource_factory.go
- openapi/resource_factory_test.go
Fix typo in error message: "This usually happends"                                                              
> Fix typo in error message

- docs/installing_openapi_provider.md
> Add git dir to script installation instructions

- scripts/install.sh
> fetch version from github instead of relying on local dir

- README.md
Readme updates to make the repo awesome:
https://github.com/avelino/awesome-go/pull/2783
> Making repo awesome

- Makefile
- main.go
- openapi/common.go
- openapi/common_test.go
- openapi/data_source_instance_factory_test.go
- openapi/openapi_client_test.go
- openapi/openapi_spec_authenticator_apikey_header_test.go
- openapi/openapi_spec_resource_schema_definition_test.go
- openapi/openapi_spec_security_definition_apikey_header_bearer_test.go
- openapi/openapi_spec_security_schemes_test.go
- openapi/openapi_v2_backend_configuration_test.go
- openapi/openapi_v2_resource_test.go
- openapi/openapi_v2_spec_analyser.go
- openapi/openapi_v2_spec_analyser_test.go
- openapi/openapiutils/openapi_utils.go
- openapi/plugin_config_schema_test.go
- openapi/plugin_config_services_test.go
- openapi/plugin_config_test.go
- openapi/provider_configuration_endpoints_test.go
- openapi/provider_configuration_test.go
- openapi/provider_factory.go
- openapi/provider_test.go
- openapi/resource_factory_test.go
- tests/e2e/test_api_utils.go
- tests/integration/int_utils_test.go
> Fix goreportcard issues

- openapi/data_source_factory.go
- openapi/data_source_factory_test.go
- openapi/openapi_spec_resource_schema_definition.go
> fix IneffAssign issues

- go.sum
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
> Bugfix 181/parent id required arrays subresources

- docs/how_to.md
- go.mod
- go.sum
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- openapi/openapi_v2_spec_analyser_test.go
- openapi/provider_test.go
- tests/e2e/gray_box_cdns_test.go
- tests/e2e/resources_test.go
> Preferred name extension (x-terraform-resource-name) on root path level

- .goreleaser.yml
> Fix gorelease warnings

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
> [NewRelease] v0.25.0

- Makefile
This is fixing a bug that's blocking the release of the httpendpoint telemetry in issue #212 
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added/updated necessary documentation (if appropriate)
> [BugFix: Issue #212] Removing extra ')' in Makefile

- openapi/plugin_config_schema_test.go
- openapi/plugin_config_telemetry_provider_httpendpoint.go
- openapi/plugin_config_telemetry_provider_httpendpoint_test.go
Please link to the issue number here: #217 
> [BugFix: Issue #217] Fix marshal nil pointer caused when marshalling TelemetryProviderHTTPEndpoint

- docs/plugin_configuration_schema.md
- examples/swaggercodegen/api/api/http_utils.go
- examples/swaggercodegen/api/api/lb_api.go
- openapi/openapi_client.go
- openapi/openapi_client_stub.go
- openapi/openapi_client_test.go
- openapi/plugin_config_telemetry.go
- openapi/plugin_config_telemetry_handler.go
- openapi/plugin_config_telemetry_handler_stub.go
- openapi/plugin_config_telemetry_handler_test.go
- openapi/plugin_config_telemetry_provider_graphite.go
- openapi/plugin_config_telemetry_provider_graphite_test.go
- openapi/plugin_config_telemetry_provider_httpendpoint.go
- openapi/plugin_config_telemetry_provider_httpendpoint_test.go
- openapi/plugin_config_telemetry_provider_stub.go
- openapi/provider_factory.go
- openapi/provider_factory_test.go
- openapi/resource_factory.go
- openapi/resource_factory_test.go
- tests/e2e/provider_plugin_configuration_test.go
- tests/integration/resource_lbs_test.go
Please link to the issue number here: #221 
> [FeatureRequest: Issue #221] Plugin submits resource information and operation performed as part of telemetry metrics

- docs/plugin_configuration_schema.md
- openapi/data_source_factory.go
- openapi/data_source_factory_test.go
- openapi/data_source_instance_factory.go
- openapi/data_source_instance_factory_test.go
- openapi/plugin_config_telemetry_handler.go
- openapi/plugin_config_telemetry_handler_test.go
- openapi/resource_factory.go
- openapi/resource_factory_test.go
- tests/e2e/provider_plugin_configuration_test.go
Please link to the issue number here: #224 
> [FeatureRequest: Issue #224] Add telemetry to data sources

- docs/how_to.md
- go.mod
- go.sum
- openapi/common.go
- openapi/common_test.go
- openapi/data_source_factory.go
- openapi/data_source_instance_factory.go
- openapi/openapi_spec_resource_schema_definition_property.go
- openapi/openapi_spec_resource_schema_definition_property_test.go
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- tests/e2e/gray_box_cdns_test.go
Please link to the issue number here: #228 
> [FeatureRequest: Issue #228] Ignore array prop ordering

- openapi/resource_factory.go
- openapi/resource_factory_test.go
Please link to the issue number here: #231 
> [BugFix: Issue #231 ] Import errors when resource to be imported does not exists

- openapi/resource_factory.go
- openapi/resource_factory_test.go
Please link to the issue number here: #236 
> [BugFix: Issue #236] Don't update the state if the import fails

- go.mod
- go.sum
- openapi/openapi_spec_resource_schema_definition_property.go
- openapi/openapi_spec_resource_schema_definition_property_test.go
Please link to the issue number here: #239 
> [BugFix: Issue #239] Ignore list items order if the property is configured with x-ignore-order

- openapi/resource_factory.go
Please link to the issue number here: #242 
> [BugFix: Issue #242] Plugin should not log payload from resource API to prevent printing sensitive props

- pkg/terraformdocsgenerator/README.md
- pkg/terraformdocsgenerator/example_provider_documentation_output.html
- pkg/terraformdocsgenerator/main.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_data_sources.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_resources.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/utils.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/utils_test.go
Please link to the issue number here: Closes #248  
> [FeatureRequest: Issue #248] Add sections to documentaton generator

- .github/PULL_REQUEST_TEMPLATE.md
Please link to the issue number here: Closes #250 
> [TechDebt: Issue #250] Update PR template to include issue closing keyword

- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_properties.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #256
> [TechDebt: Issue #256] Support description field in array items schema

- openapi/common.go
- openapi/common_test.go
- openapi/openapi_spec_resource.go
- openapi/openapi_v2_resource.go
- openapi/openapi_v2_resource_test.go
- openapi/resource_factory.go
- openapi/resource_factory_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #260 
> [TechDebt: Issue #260] Plugin execution improvements

- .goreleaser.yml
This fixes a bug in release 2.0.0 where binaries released did not contain the expected statically compiled version property values. Closes: #277
> [BugFix: Issue #277]: Fix issue where binary released did not contain the expected statically compiled version properties populated

- pkg/terraformdocsgenerator/example_provider_documentation_output.html
- pkg/terraformdocsgenerator/main.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_installation.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_test.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
- pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #280 
> [BugFix: Issue #280] Add support for rendering provider documentation including Terraform 0.13 required_providers section

- docs/how_to.md
- openapi/common.go
- openapi/common_test.go
- openapi/openapi_client.go
- openapi/resource_factory.go
- openapi/resource_factory_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #283 
> [BugFix: Issue #283] Add support for PUT operations that return 204 No Content

- .travis.yml
- Makefile
Please link to the issue number here (issue will be closed when PR is merged): Closes #296 
Pasting here the error seen for the reference:
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
- By logging into docker the rate increases are it's less likely that the pipeline will run into the rate limits
More info about rate limit here: https://www.docker.com/increase-rate-limits#:~:text=The%20rate%20limits%20of%20100,the%20six%20hour%20window%20elapses.
> [BugFix: Issue #297] Fix docker rate limit issues in Travis pipeline

- Makefile
- go.mod
- go.sum
- openapi/plugin_config.go
- openapi/provider.go
- openapi/provider_test.go
Please link to the issue number here (issue will be closed when PR is merged): Closes #300 
Summary of changes:
- Moved the logic that handled the TLSClient InsecureSkipVerify enablement from getServiceConfiguration
to the CreateSchemaProviderFromServiceConfiguration.
- Added more logging when the InsecureSkipVerify is enabled with appropriate warnings
- Added more test coverage on CreateSchemaProviderFromServiceConfiguration method
- Moved the skipVerify env variable check if the otfVarSwaggerURL is also set as it was only
used there but yet initialized outside for no particular reason.
Please put an `x` (w/o heading/trailing white spaces) in the …
> [BugFix: Issue #300]: ServiceConfiguration with InsecureSkipVerify enabled now works as expected

- README.md
- docs/publishing_provider.md
Please link to the issue number here (issue will be closed when PR is merged): Closes #303 
- [ x] Feature Request: PRs related to feature requests should have in the title `[FeatureRequest: Issue #X] <PR Title>`
> [FeatureRequest: Issue #303] Create docs for publishing OpenAPI Terraform providers in Terraform Registry

- docs/installing_openapi_provider.md
- scripts/install.sh
Please link to the issue number here (issue will be closed when PR is merged): Closes #311
As discussed on [PR-312](https://github.com/dikhan/terraform-provider-openapi/pull/312) and [PR-313](https://github.com/dikhan/terraform-provider-openapi/pull/313#pullrequestreview-762681850), created this PR on behalf of the original author (@bradthebuilder ) so we get the feedback from the pipeline (as it's triggered by me and won't have the issues when running the jobs from forks - more details [here](https://github.com/dikhan/terraform-provider-openapi/pull/312#issuecomment-925506589)) and are able to merge the PR following the branch restrictions.
Please …
> [FeatureRequest: Issue #311] Support Terraform versions greater than or equal to 1.0.0

- .travis.yml
- Travis does not allow secret env variables to be used in forks which results into all the PRs opened by external contributors to fail. By adding this docker logins will not be executed and therefore builds now may still fail due to docker free quota being reached (since the egres ip from travis is shared among all the hosts). This is preferable as at least there is a change that the build will pass, unfortunately Travis does not provide any solution for this at the moment.
Soure: https://docs.travis-ci.com/user/environment-variables/
Please link to the issue number here (issue will be closed when PR is merged): Closes #338 
What type of change does your code introduce to the …
> [BugFix: Issue #X] Skip docker login from forks

- .travis.yml
- README.md
- docs/major_version_release_notes/openapi_terraform_provider_v3.0.0.md
- docs/publishing_provider.md
- go.mod
- go.sum
Please link to the issue number here (issue will be closed when PR is merged): Closes #343 
> [TechDebt: Issue #343] Integrate Go v1.17
